### PR TITLE
finish void return type cleanup

### PR DESCRIPTION
**Pull request by pedrosousa13**
@fooman I found that it was still breaking so I cleaned up the void return types. Maybe later we can add the return void in the PHPDOC instead? What do you think? :)

### CODE REVIEW

**Comment by pedrosousa13** [comment]
@fooman I was actually reading more about this issue and we could just add a `return;`. If we do that, : void will be valid also. Relevant info: https://stackoverflow.com/questions/35482195/php7-void-return-type-not-working

**Comment by fooman** [comment]
@pedrosousa13 I am okay with just the removal here (this is after all how it was on prior versions). The 2.2.8 upgrade unfortunately back-ported the emailing behaviour from 2.3.0 which caught me off guard.

Will revisit the return type question once support for lower php versions can be dropped.

**Comment by fooman** [comment]
Thanks again for picking these up - which version of php are you currently running?

**Comment by pedrosousa13** [comment]
In this current project I'm using php 7.1

**Comment by fooman** [comment]
Do you mind sharing an error message with a stack trace as I am not 100% sure yet that I am seeing the same that you are.

**Comment by pedrosousa13** [comment]
@fooman do you have an email that I can contact you with?

**Pull request merged**
